### ISSUE TITLE
Is it possible to provide the hole project source? include lwip and drivers.

### ISSUE THREAD

**Issue by zhangshengping** [epagris/flexPTP-TM4C1294#1]
Is it possible to provide the **hole project source**? include lwip and drivers.

**Comment by epagris** [comment]
Hi!

Unfortunately, I may not include the drivers and the lwip source in this public repository, since those files are licensed under Texas Instruments' license conditions prohibiting such redistribution.

As for the lwip network driver modifications, I have attached a diff file that you can apply on the original driver. The UARTprintf modification is pretty straightforward, only a single line must be inserted, or you can also turn on preemption in the FreeRTOS scheduler settings.

[ptp_modifications.diff.txt](https://github.com/epagris/flexPTP/files/10826413/ptp_modifications.diff.txt)
